email = ""
password = ""
deltachat_db = "db/dc.sqlite"
oauth_db = "db/oauth.sled"
listen_addr = "0.0.0.0:3000"
enable_request_logging = false
static_dir = "./static/"

[oauth]

client_id = ""
client_secret = ""
redirect_uri = ""
